# Spring Application Name
spring.application.name=hotel-booking

# PostgreSQL Database Connection (Render Online DB)
spring.datasource.url=jdbc:postgresql://dpg-d6eahr94tr6s73ba9kq0-a.oregon-postgres.render.com:5432/hotelbookingdb_ucic
spring.datasource.username=hotelbookingdb_ucic_user
spring.datasource.password=aZPp2QuTqi275tBnGziyDSATEMYgIOUI
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Increase max file size
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Server binding for Render
server.address=0.0.0.0
server.port=${PORT:8080}
